CREATE TABLE USER_TABLE (
  ID_USER INTEGER PRIMARY KEY AUTO_INCREMENT,
  PSEUDO varchar(30),
  PASSWORD varchar(30),
  ISADMIN boolean
);

CREATE TABLE THEME (
  ID_THEME INTEGER PRIMARY KEY,
  NOM_THEME VARCHAR(100) 
);

CREATE TABLE QUESTION (
	ID_QUESTION INTEGER PRIMARY KEY,
	LIBELLE_QUESTION VARCHAR(100),
	ID_THEME INTEGER,
	CONSTRAINT FK_ID_THEME FOREIGN KEY (ID_THEME) REFERENCES THEME(ID_THEME)
);

CREATE TABLE REPONSE (
  ID_REPONSE INTEGER PRIMARY KEY,
  LIBELLE_REPONSE VARCHAR(100),
  VERACITE boolean ,
  ID_QUESTION INTEGER,
  CONSTRAINT FK_ID_QUESTION FOREIGN KEY (ID_QUESTION) REFERENCES QUESTION(ID_QUESTION)
);

CREATE TABLE QCM (
  ID_QCM  VARCHAR(30) PRIMARY KEY,
  ID_USER INTEGER,
  DATE  DATE,
  CONSTRAINT FK_ID_USER FOREIGN KEY (ID_USER) REFERENCES USER_TABLE(ID_USER)
);

CREATE TABLE RESULTAT (
  ID_RESULTAT INTEGER PRIMARY KEY,
  ID_QCM INTEGER,
  ID_REPONSE INTEGER,
  CONSTRAINT FK_ID_QCM FOREIGN KEY (ID_QCM) REFERENCES QCM(ID_QCM),
  CONSTRAINT FK_ID_REPONSE FOREIGN KEY (ID_REPONSE) REFERENCES REPONSE(ID_REPONSE)
);


